[package]
name = "rust-test"
version = "0.1.0"
authors = ["Tobias Tangemann <tobias@tangemann.org>"]
edition = "2018"

[dependencies]
crossbeam-channel = "0.5"
lazy_static = "1.4"
regex = "1.4"
sysinfo = "0.15"


[profile.release]
#debug = true
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
