[package]
name = "monitor-avahi"
version = "1.2.0"
authors = ["Tobias Tangemann <tobias@tangemann.org>"]
edition = "2021"

[dependencies]
hostname = "^0.3"
clap = { version = "^3.1", features = ["derive"] }
dbus = "^0.9"

[profile.release]
#debug = true
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
