[package]
name = "monitor-avahi"
version = "1.1.1"
authors = ["Tobias Tangemann <tobias@tangemann.org>"]
edition = "2021"

[dependencies]
crossbeam-channel = "0.5"
hostname = "^0.3"
lazy_static = "1.4"
regex = "1.5"
clap = { version = "3.0", features = ["derive"] }

[target.'cfg(linux)'.dependencies]
dbus = "0.9"

[profile.release]
#debug = true
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
